from __future__ import annotations

from reallang import ast_nodes as ast

_INDENT = "  "

# RealLang v0.1 defines wrapping i32 arithmetic (documented in README.md).
# TODO(backend-hardening): Lower i32 + - * / through explicit uint32_t casts (or
# fixed-width helpers) so generated C never relies on undefined signed overflow.
# Until then, the C backend assumes two's-complement wrap semantics match RealLang.


def emit_c(module: ast.Module) -> str:
    lines = [
        "// Generated by RealLang realc",
        "#include <stdio.h>",
        "#include <stdbool.h>",
        "",
    ]

    others = [fn for fn in module.functions if fn.name != "main"]
    mains = [fn for fn in module.functions if fn.name == "main"]

    for fn in others:
        lines.extend(_emit_function(fn))
        lines.append("")

    for fn in mains:
        lines.extend(_emit_function(fn, c_name="main", c_sig="int main(void)"))

    return "\n".join(lines).rstrip() + "\n"


def _emit_function(
    fn: ast.Function,
    *,
    c_name: str | None = None,
    c_sig: str | None = None,
) -> list[str]:
    name = c_name if c_name else fn.name
    if c_sig:
        header = f"{c_sig} {{"
    else:
        params = ", ".join(f"{_c_type(p.type)} {p.name}" for p in fn.params)
        header = f"{_c_type(fn.return_type)} {name}({params}) {{"

    lines = [header]
    for stmt in fn.body.statements:
        lines.extend(_emit_statement(stmt, depth=1))
    lines.append("}")
    return lines


def _pad(depth: int) -> str:
    return _INDENT * depth


def _emit_statement(stmt: ast.Stmt, *, depth: int) -> list[str]:
    pad = _pad(depth)
    if isinstance(stmt, (ast.LetStmt, ast.VarStmt)):
        return [f"{pad}{_c_type(stmt.type)} {stmt.name} = {_emit_expr(stmt.init)};"]

    if isinstance(stmt, ast.SetStmt):
        return [f"{pad}{stmt.name} = {_emit_expr(stmt.value)};"]

    if isinstance(stmt, ast.WhileStmt):
        cond = _emit_expr(stmt.condition)
        lines = [f"{pad}while ({cond}) {{"]
        for inner in stmt.body.statements:
            lines.extend(_emit_statement(inner, depth=depth + 1))
        lines.append(f"{pad}}}")
        return lines

    if isinstance(stmt, ast.IfStmt):
        cond = _emit_expr(stmt.condition)
        lines = [f"{pad}if ({cond}) {{"]
        for inner in stmt.then_body.statements:
            lines.extend(_emit_statement(inner, depth=depth + 1))
        lines.append(f"{pad}}} else {{")
        for inner in stmt.else_body.statements:
            lines.extend(_emit_statement(inner, depth=depth + 1))
        lines.append(f"{pad}}}")
        return lines

    if isinstance(stmt, ast.ExprStmt) and isinstance(stmt.expr, ast.CallExpr):
        return [f"{pad}{_emit_call(stmt.expr)};"]

    if isinstance(stmt, ast.ReturnStmt):
        return [f"{pad}return {_emit_expr(stmt.value)};"]

    raise ValueError(f"unsupported statement: {type(stmt).__name__}")


def _emit_call(call: ast.CallExpr) -> str:
    if call.callee == "print_str":
        arg = call.args[0]
        assert isinstance(arg, ast.StringLit)
        return f'printf("%s", {_c_string(arg.value)})'
    if call.callee == "print_i32":
        return f'printf("%d\\n", {_emit_expr(call.args[0])})'
    if call.callee == "print_bool":
        return f'printf("%s\\n", {_emit_bool_literal_text(call.args[0])})'
    args = ", ".join(_emit_expr(arg) for arg in call.args)
    return f"{call.callee}({args})"


def _emit_bool_literal_text(expr: ast.Expr) -> str:
    if isinstance(expr, ast.BoolLit):
        return '"true"' if expr.value else '"false"'
    return f"({_emit_expr(expr)} ? \"true\" : \"false\")"


_PREC_CMP = 1
_PREC_ADD = 2
_PREC_MUL = 3
_PREC_PRIMARY = 4


def _emit_expr(expr: ast.Expr, min_prec: int = _PREC_CMP) -> str:
    if isinstance(expr, ast.CmpExpr):
        if _PREC_CMP < min_prec:
            return f"({_emit_cmp(expr)})"
        return _emit_cmp(expr)
    if isinstance(expr, ast.BinExpr):
        return _emit_bin(expr, min_prec)
    return _emit_primary(expr)


def _emit_cmp(expr: ast.CmpExpr) -> str:
    op = {
        ast.CmpOp.LT: "<",
        ast.CmpOp.LE: "<=",
        ast.CmpOp.GT: ">",
        ast.CmpOp.GE: ">=",
        ast.CmpOp.EQ: "==",
        ast.CmpOp.NE: "!=",
    }[expr.op]
    left = _emit_expr(expr.left, _PREC_ADD)
    right = _emit_expr(expr.right, _PREC_ADD)
    return f"{left} {op} {right}"


def _emit_bin(expr: ast.BinExpr, min_prec: int) -> str:
    op_prec = _PREC_MUL if expr.op in (ast.BinOp.MUL, ast.BinOp.DIV) else _PREC_ADD
    if op_prec < min_prec:
        return f"({_emit_bin(expr, _PREC_CMP)})"

    op = {ast.BinOp.ADD: "+", ast.BinOp.SUB: "-", ast.BinOp.MUL: "*", ast.BinOp.DIV: "/"}[expr.op]
    next_prec = op_prec + 1 if expr.op in (ast.BinOp.MUL, ast.BinOp.DIV) else op_prec + 1
    left = _emit_expr(expr.left, next_prec)
    right = _emit_expr(expr.right, next_prec)
    return f"{left} {op} {right}"


def _emit_primary(expr: ast.Expr) -> str:
    if isinstance(expr, ast.IntLit):
        return str(expr.value)
    if isinstance(expr, ast.BoolLit):
        return "true" if expr.value else "false"
    if isinstance(expr, ast.IdentExpr):
        return expr.name
    if isinstance(expr, ast.CallExpr):
        return _emit_call(expr)
    if isinstance(expr, ast.StringLit):
        return _c_string(expr.value)
    raise ValueError(f"unsupported expression: {type(expr).__name__}")


def _c_type(kind: ast.TypeKind) -> str:
    if kind == ast.TypeKind.I32:
        return "int"
    if kind == ast.TypeKind.BOOL:
        return "bool"
    raise ValueError(f"unsupported C type for {kind}")


def _c_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'
