from __future__ import annotations

from reallang import ast_nodes as ast

_INDENT = "  "

_I32_MIN = -(2**31)
_I32_MAX = 2**31 - 1
_U32_MOD = 2**32


def emit_c(module: ast.Module) -> str:
    helpers = _collect_i32_helpers(module)
    includes = [
        "#include <stdio.h>",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "#include <inttypes.h>",
    ]
    if "from_u32" in helpers:
        includes.append("#include <string.h>")

    lines = [
        "// Generated by RealLang realc",
        *includes,
        "",
    ]
    helper_lines = _emit_i32_helpers(helpers)
    if helper_lines:
        lines.extend(helper_lines)
        lines.append("")

    for fn in module.functions:
        lines.append(_emit_prototype(fn))
    lines.append("")

    for fn in module.functions:
        lines.extend(_emit_function(fn))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _emit_i32_helpers(helpers: set[str]) -> list[str]:
    lines: list[str] = []
    if "from_u32" in helpers:
        lines.extend(
            [
                "static inline int32_t real_i32_from_u32(uint32_t value) {",
                "  int32_t result;",
                "  memcpy(&result, &value, sizeof(result));",
                "  return result;",
                "}",
            ]
        )
    if "add" in helpers:
        if lines:
            lines.append("")
        lines.extend(
            [
                "static inline int32_t real_i32_add(int32_t lhs, int32_t rhs) {",
                "  return real_i32_from_u32((uint32_t)lhs + (uint32_t)rhs);",
                "}",
            ]
        )
    if "sub" in helpers:
        if lines:
            lines.append("")
        lines.extend(
            [
                "static inline int32_t real_i32_sub(int32_t lhs, int32_t rhs) {",
                "  return real_i32_from_u32((uint32_t)lhs - (uint32_t)rhs);",
                "}",
            ]
        )
    if "mul" in helpers:
        if lines:
            lines.append("")
        lines.extend(
            [
                "static inline int32_t real_i32_mul(int32_t lhs, int32_t rhs) {",
                "  return real_i32_from_u32((uint32_t)lhs * (uint32_t)rhs);",
                "}",
            ]
        )
    if "div" in helpers:
        if lines:
            lines.append("")
        lines.extend(
            [
                "static inline int32_t real_i32_div(int32_t lhs, int32_t rhs) {",
                "  if (lhs == INT32_MIN && rhs == -1) {",
                "    return INT32_MIN;",
                "  }",
                "  return lhs / rhs;",
                "}",
            ]
        )
    return lines


def _emit_prototype(fn: ast.Function) -> str:
    if fn.name == "main":
        return "int main(void);"
    return f"{_c_type(fn.return_type)} {fn.name}({_c_params(fn.params)});"


def _emit_function(
    fn: ast.Function,
) -> list[str]:
    if fn.name == "main":
        header = "int main(void) {"
    else:
        header = f"{_c_type(fn.return_type)} {fn.name}({_c_params(fn.params)}) {{"

    lines = [header]
    for param in fn.params:
        lines.append(f"{_pad(1)}(void){param.name};")
    for stmt in fn.body.statements:
        lines.extend(_emit_statement(stmt, depth=1))
    lines.append("}")
    return lines


def _pad(depth: int) -> str:
    return _INDENT * depth


def _emit_statement(stmt: ast.Stmt, *, depth: int) -> list[str]:
    pad = _pad(depth)
    if isinstance(stmt, (ast.LetStmt, ast.VarStmt)):
        return [
            f"{pad}{_c_type(stmt.type)} {stmt.name} = {_emit_expr(stmt.init)};",
            f"{pad}(void){stmt.name};",
        ]

    if isinstance(stmt, ast.SetStmt):
        return [f"{pad}{stmt.name} = {_emit_expr(stmt.value)};"]

    if isinstance(stmt, ast.WhileStmt):
        cond = _emit_expr(stmt.condition)
        lines = [f"{pad}while ({cond}) {{"]
        for inner in stmt.body.statements:
            lines.extend(_emit_statement(inner, depth=depth + 1))
        lines.append(f"{pad}}}")
        return lines

    if isinstance(stmt, ast.IfStmt):
        cond = _emit_expr(stmt.condition)
        lines = [f"{pad}if ({cond}) {{"]
        for inner in stmt.then_body.statements:
            lines.extend(_emit_statement(inner, depth=depth + 1))
        lines.append(f"{pad}}} else {{")
        for inner in stmt.else_body.statements:
            lines.extend(_emit_statement(inner, depth=depth + 1))
        lines.append(f"{pad}}}")
        return lines

    if isinstance(stmt, ast.ExprStmt) and isinstance(stmt.expr, ast.CallExpr):
        return [f"{pad}{_emit_call(stmt.expr)};"]

    if isinstance(stmt, ast.ReturnStmt):
        return [f"{pad}return {_emit_expr(stmt.value)};"]

    raise ValueError(f"unsupported statement: {type(stmt).__name__}")


def _emit_call(call: ast.CallExpr) -> str:
    if call.callee == "print_str":
        arg = call.args[0]
        assert isinstance(arg, ast.StringLit)
        return f'printf("%s", {_c_string(arg.value)})'
    if call.callee == "print_i32":
        return f'printf("%" PRId32 "\\n", {_emit_expr(call.args[0])})'
    if call.callee == "print_bool":
        return f'printf("%s\\n", {_emit_bool_literal_text(call.args[0])})'
    args = ", ".join(_emit_expr(arg) for arg in call.args)
    return f"{call.callee}({args})"


def _emit_bool_literal_text(expr: ast.Expr) -> str:
    if isinstance(expr, ast.BoolLit):
        return '"true"' if expr.value else '"false"'
    return f"({_emit_expr(expr)} ? \"true\" : \"false\")"


_PREC_CMP = 1
_PREC_ADD = 2


def _emit_expr(expr: ast.Expr, min_prec: int = _PREC_CMP) -> str:
    if isinstance(expr, ast.CmpExpr):
        if _PREC_CMP < min_prec:
            return f"({_emit_cmp(expr)})"
        return _emit_cmp(expr)
    if isinstance(expr, ast.BinExpr):
        return _emit_bin(expr)
    return _emit_primary(expr)


def _emit_cmp(expr: ast.CmpExpr) -> str:
    op = {
        ast.CmpOp.LT: "<",
        ast.CmpOp.LE: "<=",
        ast.CmpOp.GT: ">",
        ast.CmpOp.GE: ">=",
        ast.CmpOp.EQ: "==",
        ast.CmpOp.NE: "!=",
    }[expr.op]
    left = _emit_expr(expr.left, _PREC_ADD)
    right = _emit_expr(expr.right, _PREC_ADD)
    return f"{left} {op} {right}"


def _emit_bin(expr: ast.BinExpr) -> str:
    helper = {
        ast.BinOp.ADD: "real_i32_add",
        ast.BinOp.SUB: "real_i32_sub",
        ast.BinOp.MUL: "real_i32_mul",
        ast.BinOp.DIV: "real_i32_div",
    }[expr.op]
    left = _emit_expr(expr.left)
    right = _emit_expr(expr.right)
    return f"{helper}({left}, {right})"


def _emit_primary(expr: ast.Expr) -> str:
    if isinstance(expr, ast.IntLit):
        return _emit_i32_literal(expr.value)
    if isinstance(expr, ast.BoolLit):
        return "true" if expr.value else "false"
    if isinstance(expr, ast.IdentExpr):
        return expr.name
    if isinstance(expr, ast.CallExpr):
        return _emit_call(expr)
    if isinstance(expr, ast.StringLit):
        return _c_string(expr.value)
    raise ValueError(f"unsupported expression: {type(expr).__name__}")


def _collect_i32_helpers(module: ast.Module) -> set[str]:
    helpers: set[str] = set()

    def need_from_u32() -> None:
        helpers.add("from_u32")

    def visit_stmt(stmt: ast.Stmt) -> None:
        if isinstance(stmt, (ast.LetStmt, ast.VarStmt)):
            visit_expr(stmt.init)
        elif isinstance(stmt, ast.SetStmt):
            visit_expr(stmt.value)
        elif isinstance(stmt, ast.WhileStmt):
            visit_expr(stmt.condition)
            for inner in stmt.body.statements:
                visit_stmt(inner)
        elif isinstance(stmt, ast.IfStmt):
            visit_expr(stmt.condition)
            for inner in stmt.then_body.statements:
                visit_stmt(inner)
            for inner in stmt.else_body.statements:
                visit_stmt(inner)
        elif isinstance(stmt, ast.ExprStmt):
            visit_expr(stmt.expr)
        elif isinstance(stmt, ast.ReturnStmt):
            visit_expr(stmt.value)

    def visit_expr(expr: ast.Expr) -> None:
        if isinstance(expr, ast.IntLit):
            if expr.value < _I32_MIN or expr.value > _I32_MAX:
                need_from_u32()
        elif isinstance(expr, ast.BinExpr):
            if expr.op == ast.BinOp.ADD:
                helpers.add("add")
                need_from_u32()
            elif expr.op == ast.BinOp.SUB:
                helpers.add("sub")
                need_from_u32()
            elif expr.op == ast.BinOp.MUL:
                helpers.add("mul")
                need_from_u32()
            elif expr.op == ast.BinOp.DIV:
                helpers.add("div")
            visit_expr(expr.left)
            visit_expr(expr.right)
        elif isinstance(expr, ast.CmpExpr):
            visit_expr(expr.left)
            visit_expr(expr.right)
        elif isinstance(expr, ast.CallExpr):
            for arg in expr.args:
                visit_expr(arg)

    for fn in module.functions:
        for stmt in fn.body.statements:
            visit_stmt(stmt)
    return helpers


def _c_type(kind: ast.TypeKind) -> str:
    if kind == ast.TypeKind.I32:
        return "int32_t"
    if kind == ast.TypeKind.BOOL:
        return "bool"
    raise ValueError(f"unsupported C type for {kind}")


def _c_params(params: list[ast.Param]) -> str:
    if not params:
        return "void"
    return ", ".join(f"{_c_type(p.type)} {p.name}" for p in params)


def _emit_i32_literal(value: int) -> str:
    if _I32_MIN <= value <= _I32_MAX:
        return str(value)
    return f"real_i32_from_u32(UINT32_C({value % _U32_MOD}))"


def _c_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'
