from __future__ import annotations

import json
import re
from dataclasses import dataclass


@dataclass(frozen=True)
class PlanStep:
    order: int
    action: str
    detail: str


@dataclass(frozen=True)
class AgentPlan:
    task: str
    summary: str
    steps: list[PlanStep]


def format_plan(plan: AgentPlan) -> str:
    lines = [f"Task: {plan.task}", f"Summary: {plan.summary}", "Steps:"]
    for step in plan.steps:
        lines.append(f"  {step.order}. [{step.action}] {step.detail}")
    return "\n".join(lines)


def mock_plan_for_task(task: str) -> AgentPlan:
    """Deterministic plan template used by MockProvider and tests."""
    normalized = task.strip() or "(empty task)"
    return AgentPlan(
        task=normalized,
        summary="Inspect RealLang sources with realc, apply only safe rule-based repairs.",
        steps=[
            PlanStep(1, "index", "Scan workspace for .real files relevant to the task."),
            PlanStep(2, "check", f"Run realc --check on files related to: {normalized}"),
            PlanStep(3, "diagnose", "Parse structured REAL_*_ERROR diagnostics from stderr."),
            PlanStep(
                4,
                "repair",
                "Apply conservative E203 let→var repairs only when proven safe.",
            ),
            PlanStep(5, "verify", "Rerun realc --check and report pass/fail."),
        ],
    )


def parse_plan_response(task: str, text: str) -> AgentPlan:
    normalized = task.strip() or "(empty task)"
    payload = json.loads(text) if text.strip().startswith("{") else _extract_json(text)
    summary = str(payload.get("summary", "")).strip() or "Plan generated by local model."
    raw_steps = payload.get("steps", [])
    steps: list[PlanStep] = []
    if isinstance(raw_steps, list):
        for index, item in enumerate(raw_steps, start=1):
            if not isinstance(item, dict):
                continue
            order = int(item.get("order", index))
            action = str(item.get("action", "step")).strip() or "step"
            detail = str(item.get("detail", "")).strip() or action
            steps.append(PlanStep(order=order, action=action, detail=detail))
    if not steps:
        raise ValueError("model plan JSON contained no usable steps")
    return AgentPlan(task=normalized, summary=summary, steps=steps)


def _extract_json(text: str) -> dict:
    stripped = text.strip()
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", stripped, re.DOTALL)
    if fenced:
        return json.loads(fenced.group(1))
    start = stripped.find("{")
    end = stripped.rfind("}")
    if start != -1 and end != -1 and end > start:
        return json.loads(stripped[start : end + 1])
    raise ValueError("no JSON object found in model response")
