from __future__ import annotations

from realforge.multimodal.models import (
    ImageGenerationRequest,
    MultimodalCapabilities,
    VisionRequest,
)
from realforge.multimodal.provider_base import (
    ImagePromptProviderOutput,
    MultimodalProvider,
    VisionProviderOutput,
)


MOCK_MAX_IMAGES = 4
MOCK_MAX_IMAGE_BYTES = 8 * 1024 * 1024


class MockMultimodalProvider(MultimodalProvider):
    """Deterministic workflow provider; performs no semantic image recognition."""

    @property
    def name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str | None:
        return "mock-multimodal"

    def capabilities(self) -> MultimodalCapabilities:
        return MultimodalCapabilities(
            provider=self.name,
            model=self.model_name,
            supports_text=True,
            supports_vision=True,
            supports_image_generation=True,
            supports_embeddings=False,
            max_images=MOCK_MAX_IMAGES,
            max_image_bytes=MOCK_MAX_IMAGE_BYTES,
            notes=(
                "Vision support validates workflow wiring only; no semantic recognition is performed.",
                "Image generation support returns prompt_spec JSON only; no binary image is generated.",
            ),
            experimental=True,
        )

    def analyze_vision(self, request: VisionRequest) -> VisionProviderOutput:
        return VisionProviderOutput(
            observed_elements=(),
            style_notes=("No semantic style analysis was performed by the mock provider.",),
            likely_use_cases=("Validate local multimodal workflow and report integration.",),
            risks=("Do not interpret deterministic mock output as image understanding.",),
            limitations=(
                "MockMultimodalProvider does not inspect semantic image content.",
                "Only trusted ImageInput hash and metadata descriptors were supplied.",
            ),
            confidence=0.0,
        )

    def build_image_prompt(self, request: ImageGenerationRequest) -> ImagePromptProviderOutput:
        style = ", ".join(request.style_notes) if request.style_notes else "purpose-driven concept art"
        use_case = request.target_use_case or "concept exploration"
        brief = f" Brief: {request.brief.strip()}." if request.brief and request.brief.strip() else ""
        return ImagePromptProviderOutput(
            prompt=f"{request.task.strip()}. Intended use: {use_case}.{brief}",
            negative_prompt="unreadable focal point, accidental text, unclear silhouette",
            style=style,
            composition="single readable focal subject with clear foreground and background separation",
            lighting="controlled cinematic lighting that preserves subject readability",
            camera="neutral concept-art camera selected for clear inspection",
            materials=("materials must be specified or validated before production",),
            constraints=(
                "prompt specification only",
                "no binary image generated by RealForge 2.3",
                "human review required before use with an image model",
            ),
            intended_tool=None,
            risks=("Generated results from future image tools may not match this specification.",),
        )
